# Generated by Django 2.2.3 on 2019-08-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='company_detail',
        ),
    ]
